# Default make rules

# Default rule
obj-dirs := $(addprefix $(BUILD)/, $(filter %/, $(obj-y)))
obj-files := $(addprefix $(BUILD)/, $(filter-out %/, $(obj-y)))
all: $(BUILD)/modules.o
	$(info $(RELAPATH): built $^)

# Dependencies
bdeps := $(obj-files)
bdeps := $(bdeps:.o=.d)
bdeps := $(bdeps:.i=.d)
bdeps := $(bdeps:.s=.d)
-include $(bdeps)

$(BUILD)/%.d:
	$(NOOP)

# Rule for errors
.DEFAULT:
	$(error No rules for $@ (deps = $^) (pwd = $(shell pwd)))

# Rule for directories
alldirs := $(addprefix $(BUILD)/, $(wildcard */))
.PHONY: $(alldirs)
$(alldirs):
	$(info $(relapath): descending into $@)
	$(Q)$(MAKE) -C $(dir $@) SRC_ROOT=$(SRC_ROOT) BUILD_ROOT=$(BUILD_ROOT) $(MAKECMDGOALS)

# Rule for modules.o
allmods := $(addsuffix modules.o, $(addprefix $(BUILD)/, $(wildcard */)))
$(BUILD)/%/modules.o: $(BUILD)/%/
	$(NOOP)

.PHONY: $(BUILD)/modules.o
$(BUILD)/modules.o: $(obj-files) $(addsuffix modules.o, $(obj-dirs))
	$(LD) -r -o $@ $^

# Don't build source files
noop := $(wildcard $(BUILD_ROOT)/.config $(SRC_ROOT)/Makefile.* Makefile $(SRC)/*.c)
$(noop):
	$(NOOP)

# Clean rule
clean-dirs := $(addprefix $(BUILD)/, $(filter %/, $(obj-y) $(obj-) $(clean-y)))
clean-files := $(addprefix $(BUILD)/, $(filter-out %/, $(obj-y) $(obj-) $(clean-y)))
.PHONY: clean
clean: $(clean-dirs)
	$(info bdeps = $(bdeps))
	rm -f $(clean-files) $(bdeps) $(BUILD)/modules.o

# Generic build rules

$(BUILD)/%.i: $(SRC)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -E -o $@ $<

$(BUILD)/%.i: $(BUILD)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -E -o $@ $<

$(BUILD)/%.s: $(SRC)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -S -o $@ $<

$(BUILD)/%.s: $(BUILD)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -S -o $@ $<

$(BUILD)/%.s: $(BUILD)/%.i
	$(CC) $(CFLAGS) -S -o $@ $<

$(BUILD)/%.s: $(SRC)/%.S
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -E -o $@ $<

$(BUILD)/%.s: $(BUILD)/%.S
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -E -o $@ $<

$(BUILD)/%.o: $(SRC)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

$(BUILD)/%.o: $(BUILD)/%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

$(BUILD)/%.o: $(BUILD)/%.i
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD)/%.o: $(SRC)/%.S
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

$(BUILD)/%.o: $(BUILD)/%.S
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

$(BUILD)/%.o: $(BUILD)/%.s
	$(CC) $(CFLAGS) -c -o $@ $<
