include $(SRC_ROOT)/scripts/make/flags.mk

boot-y = break.o panic.o device.o cmdline.o halt.o sched/ compiler/

obj-y = break.o panic.o device.o init.o cmdline.o halt.o task.o sched/ compiler/

include $(SRC_ROOT)/scripts/make/rules.mk
