include $(SRC_ROOT)/Makefile.flags

bootloader-y = panic.o device.o cmdline.o halt.o sched/

obj-y = panic.o device.o init.o cmdline.o halt.o task.o sched/
#obj-y += test.o

include $(SRC_ROOT)/Makefile.rules
