#!/bin/sh
set -eu

shquote() {
	LC_ALL=C awk -v q="'" '
		BEGIN{
			for (i=1; i<ARGC; i++) {
				gsub(q, q "\\" q q, ARGV[i])
				printf "%s ", q ARGV[i] q
			}
		}' "$@"
}

[ "${1:-}" = -e ] || exec env -i -- "$0" -e
. "$(pwd)"/.config
set | grep '^CONFIG_' | while read -r line; do
	printf -- "-D%s " "${line}"
done
