#!/usr/bin/env python

import subprocess
import sys
from collections import defaultdict

proc = subprocess.run(['errno', '-l'], check=True,
                      stdout=subprocess.PIPE, stderr=None)
errno = defaultdict(lambda: {'name': '', 'desc': ''})
errno[0] = {'name': 'SUCCESS', 'desc': 'Success'}

for line in proc.stdout.decode('UTF-8').split('\n'):
    line = line.strip()
    if not line:
        continue
    split = line.split(' ')
    name = split[0]
    code = int(split[1])
    desc = ' '.join(split[2:])
    #sys.stderr.write(f"{name} [{code}]: {desc}\n")
    if errno[code]['name']:
        errno[code]['name'] += ' '
    else:
        errno[code]['desc'] = desc
    errno[code]['name'] += name

sys.stdout.write(
    "const char * strerr(int err)\n"
    "{\n"
    "\tswitch (err) {\n"
)
for code in sorted(errno):
    info = errno[code]
    sys.stdout.write(
        f"\tcase {code}: // {info['name']}\n"
        f"\t\treturn \"{info['desc']}\";\n"
    )
sys.stdout.write(
    "\tdefault:\n"
    "\t\treturn \"Unknown error\";\n"
    "\t}\n"
    "}\n"
)
