include $(SRC_ROOT)/scripts/make/flags.mk

obj-y = console.o printf.o printk.o string.o unicode.o strtox.o
boot-y = console.o printf.o printk.o string.o unicode.o strtox.o

include $(SRC_ROOT)/scripts/make/rules.mk
