include $(SRC_ROOT)/Makefile.flags

obj-y = console.o printf.o printk.o string.o unicode.o strtox.o
bootloader-y = console.o printf.o printk.o string.o unicode.o strtox.o

include $(SRC_ROOT)/Makefile.rules
